#####################################################################
# Proposed additional keywords
#
# systemAlias: For implementation. Allows properties to be stored as
#     different keywords.  The property listed in the properties
#     section is what the user will refer to it, and the systemAlias
#     value is what it will be stored in the database as.
#
# systemProperties: The property keys listed under systemProperties
#     are properties that the submitter is not allowed to update.
#
# parentType: The type of object that the parent relationship points
#     to.
#
#####################################################################

$schema: "http://json-schema.org/draft-04/schema#"

#####################################################################
# Aliquot
#####################################################################

aliquot:

# Aliquot meta
  title: Aliquot
  type: object
  namespace: http://gdc.nci.nih.gov
  category: biospecimen
  project: '*'
  description: "TODO"
  additionalProperties: false
  validators: []

  schemaProperties:
    version: 1
    created_date: "2015-06-16T07:37:39Z"
    updated_date: "2015-07-12T21:04:01Z"
    is_published: false

  systemProperties:
    - aliquot_id
    - project

  required:
    - submitter_aliquot_id
    - parents

  unique_keys:
    - [aliquot_id]
    - [project_id, submitter_aliquot_id]

# Aliquot properties
  properties:
    type:
      type: string
    aliquot_id:
      $ref: "definitions.yaml#/UUID"
      systemAlias: node_id
      description: "TODO"
    submitter_aliquot_id:
      type: string
      description: "TODO"
    submitter_case_id:
      type: string
      description: "TODO"
    submitter_analyte_id:
      type: string
      description: "TODO"
    submitter_sample_id:
      type: string
      description: "TODO"

# Aliquot parents
    parents:
      type: object
      additionalProperties: false
      required:
        - analyte_ids
      properties:
        analyte_ids:
          $ref: "definitions.yaml#/parent_uuids"
          parentType: analyte
